spring:
  application:
    name: Design
  datasource:
    url: jdbc:mysql://localhost/chen?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 456718293
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect  
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
mybatis:
  mapper-locations:
  - mapper/*.xml